# ----------- CONFIGURABLE START -----------
title:            "tori vaz"
description:      "a personal site"
url:              http://torivaz.com # Site url, without a slash at the end.
signoff:          "tori" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         home
    url:          /
    external:     false
  - name:         about
    url:          /about
    external:     false
  - name:         projects
    url:          /projects
    external:     false
  - name:         cv
    url:          /cv
    external:     false
# ------------ CONFIGURABLE END ------------
permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
plugins:
  - jemoji
