# ----------- CONFIGURABLE START -----------
title:            "tori vaz"
description:      "a personal site"
url:              http://torivaz.com # Site url, without a slash at the end.
signoff:          "tori" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         posts
    url:          /
    external:     false
  - name:         about
    url:          /about
    external:     false
  - name:         podcasts
    url:          /podcasts
    external:     false
  - name:         panels
    url:          /panels
    external:     false
  - name:         cv
    url:          /cv
    external:     false
  - name:	  the omen chronicles
    url:	  https://www.omenchroniclescomic.com/
    external:	  true
# ------------ CONFIGURABLE END ------------
permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
plugins:
  - jemoji
